# Site settings
title: Bronwyn Campbell
email: Bronwyn.Campbell@mq.edu.au
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: bronwyncc
github_username: bronwyncc

# Build settings
markdown: kramdown
